Zaimportuj bibliotekę numpy (użyj aliasu np). Zdefiniuj dwie tablice:

x = np.arange(0, 60, 10) \
y = np.array([7, 35, 22, 19, 40, 39])

In [42]:
import numpy as np

x = np.arange(0, 60, 10)
y = np.array([7, 35, 22, 19, 40, 39])

print(x)
print(y)

[ 0 10 20 30 40 50]
[ 7 35 22 19 40 39]


a) Oblicz na ilu pozycjach wartości w wektorze x są większe niż w wektorze y.

In [18]:
np.sum(x>y)

2

b) Oblicz jaka jest średnia różnica między wartościami w wektorach x i y.

In [19]:
np.mean(y-x)

2.0

c) Oblicz jaka jest średnia z wartości bezwzględnych różnic między wartościami w wektorach x i y.

In [20]:
np.mean(np.abs(y-x))

9.333333333333334

d) Oblicz jaka jest średnia z wartość kwadratu różnic między wartościami w wektorach x i y.

In [22]:
np.mean((y-x)**2)

153.33333333333334

e) Oblicz na ilu pozycjach wektory x i y różnią się o więcej niż 10.

In [45]:
np.sum(np.abs(y-x) > 10)

3

f) Zwróć te wartości z tablicy x, których pierwiastek nie różni się o więcej niż 1 od pierwiastka z wartości w wektorze y, stojących na odpowiadających im pozycjach.

In [28]:
x[np.abs(np.sqrt(x)-np.sqrt(y)) <= 1]

array([20, 40, 50])

g) Zwróć te elementy z wektora x, które od wartości najmniejszej w wektorze x nie różnią się o więcej niż 30.

In [32]:
x[x-np.min(x) <= 30]

array([ 0, 10, 20, 30])

h) Zamień w wektorze x wartości większe niż średnia z wartości wektora x na wartość 10.

In [38]:
x = np.where(x > np.mean(x), 10, x)
print(x)

[ 0 10 10 10 10 10]
