In [70]:
import numpy as np
M = np.arange(20).reshape((4, 5))
M

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

a) Często stosowanym zabiegiem podczas przygotowywania danych do nauki algorytmów uczenia maszynowego jest standaryzacja danych, która polega na tym, że w każdej kolumnie danej macierzy liczb od wszystkich wartości w kolumnie odejmujemy średnią z kolumny i dzielimy te różnice przez odchylenie standardowe w danej kolumnie. Zaimplementuj standaryzację i dla przykładowej macierzy oblicz średnie i odchylenia standardowe w kolumnach po standaryzacji.

In [74]:
a = M
a = a - np.mean(a, 0)
a = a / np.std(a, 0)
print(a)
print(np.mean(a, 0))
print(np.std(a, 0))

[[-1.34164079 -1.34164079 -1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079  1.34164079  1.34164079]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


b) Czasem również wykorzystywane jest przekształcenie polegające na tym, że dzielimy wartości w każdej kolumnie przez wartość największą w danej kolumnie. Zaimplementuj tę transformację i dla przykładowej macierzy o wartościach dodatnich, oblicz wartości maksymalne w kolumnach po takim przekształceniu macierzy.

In [75]:
b = M
b = b / np.max(b, 0)
print(b)
print(np.max(b, 0))

[[0.         0.0625     0.11764706 0.16666667 0.21052632]
 [0.33333333 0.375      0.41176471 0.44444444 0.47368421]
 [0.66666667 0.6875     0.70588235 0.72222222 0.73684211]
 [1.         1.         1.         1.         1.        ]]
[1. 1. 1. 1. 1.]


c) Innym użytecznym zabiegiem jest tzw. normalizacja wierszy, która może być realizowana w różnych wariantach. Zaimplementuj normalizację macierzy polegającą na tym, że każdy wiersz (wszystkie wartości w wierszu) dzielimy przez sumę wartości w danym wierszu oraz taką, która polega na tym, że wiersze dzielimy przez pierwiastek z sumy kwadratów wartości w danym wierszu (czyli przez tzw. normę euklidesową wektora).

In [98]:
c = M
c = c / np.sum(c, 1).reshape(np.size(c, 0), 1)
print(c)

[[0.         0.1        0.2        0.3        0.4       ]
 [0.14285714 0.17142857 0.2        0.22857143 0.25714286]
 [0.16666667 0.18333333 0.2        0.21666667 0.23333333]
 [0.17647059 0.18823529 0.2        0.21176471 0.22352941]]


In [102]:
d = M
d = d / np.sqrt(np.sum(d**2, 1)).reshape(np.size(d, 0), 1)
print(d)

[[0.         0.18257419 0.36514837 0.54772256 0.73029674]
 [0.31311215 0.37573457 0.438357   0.50097943 0.56360186]
 [0.37011661 0.40712827 0.44413993 0.48115159 0.51816325]
 [0.39324188 0.419458   0.44567413 0.47189025 0.49810638]]
