In [2]:
np.empty([1,2])

array([[-2.0000000e+000,  6.9532796e-310]])

In [1]:
from IPython.core.display import display, HTML; display(HTML("<style>.container{width:90% !important;}</style>")) 

In [2]:
import numpy as np

#### Zadanie 1.1.1:
Utwórz niżej opisane tablice. Nie musisz przypisywać ich do zmiennych. Wybierz taki sposób tworzenia tablicy jaki będzie najbardziej odpowiedni.

- wektor zawierający 6 kolejnych cyfr ciągu Fibonacciego 
- wektor zawierający 5 kolejnych potęg liczby 2 (zaczynając od wykładnika =0)
- wektor zawierający co trzecią liczbę z przedziału [5, 39)
- wektor zawierający 28 równomiernie rozłożonych wartości z przedziału [20, 40]

In [5]:
np.array([1, 1, 2, 3, 5, 8])

array([1, 1, 2, 3, 5, 8])

In [6]:
np.array([1, 2, 4, 8, 16])

array([ 1,  2,  4,  8, 16])

In [7]:
np.arange(5, 39, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

In [8]:
np.linspace(20, 40, 28)

array([20.        , 20.74074074, 21.48148148, 22.22222222, 22.96296296,
       23.7037037 , 24.44444444, 25.18518519, 25.92592593, 26.66666667,
       27.40740741, 28.14814815, 28.88888889, 29.62962963, 30.37037037,
       31.11111111, 31.85185185, 32.59259259, 33.33333333, 34.07407407,
       34.81481481, 35.55555556, 36.2962963 , 37.03703704, 37.77777778,
       38.51851852, 39.25925926, 40.        ])

#### Zadanie 1.1.2:
Utwórz macierz, która będzie zawierała tabliczkę mnożenia dla liczb z przedziału 1-4

In [9]:
np.array([
    [1, 2, 3, 4],
    [2, 4, 6, 8],
    [3, 6, 9, 12],
    [4, 8, 12, 16]
])

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

#### Zadanie 3
- Utwórz macierz samych jedynek o wymiarze 3x4
- Utwórz tablicę samych zer o wymiarze 2x5x3
- Utwórz macierz jednostkową o wymiarze 4x4

In [14]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros([2, 5, 3])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Zadanie 1.2.1:
Wybierz jedną tablicę z poprzedniego zadania i zapisz ją do pliku w katalogu `dumps`. Nie nadpisz żadnego z istniejacych tam plików.

In [17]:
array_to_dump = np.array([1, 2, 4, 8, 16])
np.save('dumps/my_array.npy', array_to_dump)

#### Zadanie 1.2.2:
Wczytaj zapisaną przed chwilą tablicę. Nie musisz przypisywać jej do żadnej zmiennej

In [18]:
np.load('dumps/my_array.npy')

array([ 1,  2,  4,  8, 16])

#### Zadanie 1.3.1:
Wczytaj pliki `dump_1_3_1.npy`, `dump_1_3_2.npy` oraz `dump_1_3_3.npy` i sprawdź ile mają wymiarów oraz jaki jest ich kształt. Przypisz je do zmiennych (będziemy z nich korzystać w kolejnych zadaniach)

In [19]:
# Q = np.arange(64).reshape(8, 8).astype('float')
# np.save('dumps/dump_1_3_1.npy', Q)

# Q = np.arange(64).reshape(2, 4, 8).astype('str')
# np.save('dumps/dump_1_3_2.npy', Q)

# Q = np.arange(6)
# np.save('dumps/dump_1_3_3.npy', Q)

In [20]:
d1 = np.load('dumps/dump_1_3_1.npy')
d2 = np.load('dumps/dump_1_3_2.npy')
d3 = np.load('dumps/dump_1_3_3.npy')

In [21]:
print(d1.ndim)
print(d2.ndim)
print(d3.ndim)

2
3
1


In [22]:
print(d1.shape)
print(d2.shape)
print(d3.shape)

(8, 8)
(2, 4, 8)
(6,)


#### Zadanie 1.4.1:
Sprawdź jakich typów są tablice wczytane w poprzednim zadaniu

In [1]:
print(d1.dtype)
print(d2.dtype)
print(d3.dtype)

NameError: name 'd1' is not defined

#### Zadanie 1.4.2:
Spróbuj zmienić typy danych

In [26]:
d1.astype(int)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [27]:
d2.astype(int)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [28]:
d3.astype(float)

array([0, 1, 2, 3, 4, 5])

#### Zadanie 1.5.1:
Sprawdź ile pamięci zajmują obiekty wczytane w poprzednim zadaniu oraz ile zajmuje pojedynczy element

In [31]:
print(d1.itemsize)
print(d2.itemsize)
print(d3.itemsize)

8
84
8


In [32]:
print(d1.nbytes)
print(d2.nbytes)
print(d3.nbytes)

512
5376
48


#### Zadanie 2.1.1:
Wyciągnij następujące slice'y z wektora `dump_2_1.npy`
- `array([ 4, -2])`
- `array([ 3,  4, -2,  0,  7,  9, -4])`
- `array([ 9, -4])` (użyj ujemnych indeksów)
- `array([ 1, -2,  9])`

In [33]:
d4 = np.load('dumps/dump_2_1.npy')

In [34]:
d4[2:4]

array([ 4, -2])

In [35]:
d4[1:-1]

array([ 3,  4, -2,  0,  7,  9, -4])

In [36]:
d4[-3:-1]

array([ 9, -4])

In [37]:
d4[::3]

array([ 1, -2,  9])

#### Zadanie 2.2.1:
Wyciągnij następujące slice'y z macierzy `dump_2_2_1.npy` oraz `dump_2_2_2.npy`

##### dump_2_2_1
- `array([-3,  1,  0,  1,  4])`
- `array([1, 0])`
- `array([[-2,  4], [6,  8]])`
- `array([0, 1, 4])`

##### dump_2_2_2
- `array([3, 4])`
- `array([[19, 20, 21], [25, 26, 27]])`

In [38]:
d5 = np.load('dumps/dump_2_2_1.npy')
d6 = np.load('dumps/dump_2_2_2.npy')

In [39]:
d5

array([[ 3,  0, -2,  4,  5],
       [ 1,  4,  6,  8, -1],
       [-3,  1,  0,  1,  4]])

In [40]:
d6

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [41]:
d5[2, :]

array([-3,  1,  0,  1,  4])

In [42]:
d5[2, 1:3]

array([1, 0])

In [43]:
d5[0:2, 2:4]

array([[-2,  4],
       [ 6,  8]])

In [44]:
d5[2, 2:5]

array([0, 1, 4])

In [45]:
d6[0, 0, 3:5]

array([3, 4])

In [46]:
d6[1, 0:2, 1:4]

array([[19, 20, 21],
       [25, 26, 27]])

#### Zadanie 2.3.1:

Wyciągnij następujące slice'y z macierzy `dump_2_3.npy` korzystając z warunków logicznych

- `array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])`
- `array([25, 26, 27, 28, 29])`
- `array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34])`

In [47]:
d7 = np.load('dumps/dump_2_3.npy')

In [48]:
d7

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [49]:
d7[d7 >= 25]

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [50]:
d7[(d7 >= 25) & (d7 <= 29)]

array([25, 26, 27, 28, 29])

In [51]:
d7[d7 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34])

#### Zadanie 2.4.1:
Wczytaj tablicę `dump_2_4.npy` a następnie zmień jej kształt na (2, 4, 8), potem na (8, 8) a finalnie na (2, 2, 16)

In [55]:
# Q = np.arange(64)

# np.save('dumps/dump_2_4_1.npy', Q)

In [56]:
d8 = np.load('dumps/dump_2_4_1.npy')

In [57]:
d8.reshape(2, 4, 8)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [58]:
d8.reshape(8, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [59]:
d8.reshape(2, 2, 16)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]]])

#### Zadanie 2.4.2:
Utwórz wektor o elementach `[1, 2, 3, 4]` a następnie go stransponuj

In [96]:
d9 = np.array([[1, 2, 3, 4]])

In [97]:
np.transpose(d9)

array([[1],
       [2],
       [3],
       [4]])

In [98]:
d9.reshape(4, 1)

array([[1],
       [2],
       [3],
       [4]])

#### Zadanie 2.4.3:
Wczytaj macierz `dump_2_4_2.npy` a następnie ją stransposnuj

In [63]:
# Q = np.arange(64).reshape(8, 8)

# np.save('dumps/dump_2_4_2.npy', Q)

In [64]:
d10 = np.load('dumps/dump_2_4_2.npy')

In [65]:
np.transpose(d10)

array([[ 0,  8, 16, 24, 32, 40, 48, 56],
       [ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63]])

In [66]:
d10

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

#### Zadanie 2.6.1:
Zaimplementuj mnożenie macierzy bez wykorzystania wbudowanej funkcji

In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

B = np.array([[1, 2, 3, 4, 5, 6],
              [4, 5, 6, 1, 2, 3],
              [7, 8, 9, 0, 1, 2]])

In [3]:
np.dot(A, B)

array([[ 30,  36,  42,   6,  12,  18],
       [ 66,  81,  96,  21,  36,  51],
       [102, 126, 150,  36,  60,  84],
       [138, 171, 204,  51,  84, 117]])

---

In [4]:
C = np.zeros([A.shape[0], B.shape[1]], dtype=np.int_)
C

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [5]:
for i in range(C.shape[0]):
    for j in range(C.shape[1]):
        C[i, j] = sum(A[i, :] * B[:, j])

In [6]:
C

array([[ 30,  36,  42,   6,  12,  18],
       [ 66,  81,  96,  21,  36,  51],
       [102, 126, 150,  36,  60,  84],
       [138, 171, 204,  51,  84, 117]])

#### Zadanie 2.6.1:
Wczytaj macierz `dump_2_6.npy` i na każdym jej wierszu wywołaj 4 metody poznane przed chwilą. Zinterpretuj wyniki i zastanów się dlaczego właśnie takich należało się spodziewać

In [2]:
d11 = np.load('dumps/dump_2_6.npy')

In [3]:
d11

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [nan, inf,  1.,  0.],
       [inf, -1.,  0.,  1.]])

In [ ]:
for i in range(d11.shape[0]):
    print(any(d11[i]))
    print(all(d11[i]))
    print(np.isnan(d11[i]))
    
    print("\n")

In [4]:
print(any(d11[0]))

print(all(d11[0]))

print(np.isnan(d11[0]))

False
False
[ True  True  True  True]
[False False False False]


In [5]:
print(any(d11[1]))

print(all(d11[1]))

print(np.isnan(d11[1]))

True
False
[ True  True  True  True]
[False False False False]


In [6]:
print(any(d11[2]))

print(all(d11[2]))

print(np.isnan(d11[2]))

True
False
[False False  True  True]
[ True False False False]


In [7]:
print(any(d11[3]))

print(all(d11[3]))

print(np.isnan(d11[3]))

True
False
[False  True  True  True]
[False False False False]


In [83]:
# Q = np.array([
#     [0, 0, 0, 0],
#     [1, 0, 0, 0],
#     [np.nan, np.inf, 1, 0],
#     [np.inf, -1, 0, 1]
# ])
# np.save('dumps/dump_2_7.npy', Q)

#### Zadanie 3.1.1:
Rozwiąż poniższe układy równań

$$\begin{align*} 
4x_1 + 8x_2 &=  24 \\ 
x_1 - 2x_2 &=  -2
\end{align*}$$

In [11]:
A = np.array([[4, 8], [1, -2]])
b = np.array([24, -2]).reshape(2, 1)

x = np.linalg.solve(A, b)
x

array([2., 2.])

$$\begin{align*} 
x_2 - x_1 &=  -3 \\ 
2x_1 + 2x_2 &=  10
\end{align*}$$

Zwróć uwagę na kolejność niewiadomych w równaniach!

In [85]:
A = np.array([[-1, 1], [2, 2]])
b = np.array([-3, 10]).reshape(2, 1)

x = np.linalg.solve(A, b)
x

array([[4.],
       [1.]])

$$\begin{align*} 
x_1 + x_2 + x_3 &=  6 \\ 
2x_1 - x_2 + 3x_3 &=  9 \\
-x_1 + x_2 - x_3 &= -2
\end{align*}$$

In [86]:
A = np.array([[1, 1, 1], [2, -1, 3], [-1, 1, -1]])
b = np.array([6, 9, -2]).reshape(3, 1)

x = np.linalg.solve(A, b)
x

array([[1.],
       [2.],
       [3.]])

#### Zadanie 4.1.1 
Wczytaj macierz `dump_4_1_1.npy` i wyznacz macierze, w których znajdą się:
- pierwiastki kwadratowe
- exponenty
- wartości bezwzględne

wszystkich elementów

In [92]:
# Q = np.array([
#     [-1, 0, 1, 2],
#     [10, 20, 30, 40],
#     [2, -4, 6, -8]
# ])
# np.save('dumps/dump_4_1_1.npy', Q)

In [93]:
d12 = np.load('dumps/dump_4_1_1.npy')
d12

array([[-1,  0,  1,  2],
       [10, 20, 30, 40],
       [ 2, -4,  6, -8]])

In [95]:
np.sqrt(d12)

<ipython-input-95-3bf4e7a75e5b>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(d12)


array([[       nan, 0.        , 1.        , 1.41421356],
       [3.16227766, 4.47213595, 5.47722558, 6.32455532],
       [1.41421356,        nan, 2.44948974,        nan]])

In [96]:
np.exp(d12)

array([[3.67879441e-01, 1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17],
       [7.38905610e+00, 1.83156389e-02, 4.03428793e+02, 3.35462628e-04]])

In [97]:
np.abs(d12)

array([[ 1,  0,  1,  2],
       [10, 20, 30, 40],
       [ 2,  4,  6,  8]])

#### Zadanie 4.1.2
Wczytaj macierz `dump_4_1_2.npy`. Wyciągnij dwa pierwsze wiersze do zmiennych jako wektory. Następnie policz logarytm dziesiętny elementów pierwszego wektora oraz logarytm naturalny elementów drugiego wektora. Dodaj do siebie te dwa wektory logarytmów.

In [98]:
# Q = np.array([
#     [2, 4, 6, 8],
#     [3, 6, 9, 12],
#     [0, 0, 0, 0]
# ])
# np.save('dumps/dump_4_1_2.npy', Q)

In [99]:
d13 = np.load('dumps/dump_4_1_2.npy')

In [100]:
d13

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 0,  0,  0,  0]])

In [101]:
x1 = d13[0, :]
x2 = d13[1, :]

In [102]:
np.log10(x1) + np.log(x2)

array([1.39964228, 2.39381946, 2.97537583, 3.38799664])

#### Zadanie 4.2.1
Wczytaj `dump_4_2.npy` i posortuj macierz według wierszy. Następnie wyciągnij wszystkie wiersze (nieposortowane) do osobnych zmiennych i posortuj je niezależnie.

In [141]:
# Q = np.array([
#     [1, 3, 2],
#     [-1, -3, -2],
#     [0, 2, 1]
# ])
# np.save('dumps/dump_4_2.npy', Q)

In [1]:
d14 = np.load('dumps/dump_4_2.npy')

In [2]:
d14

array([[ 1,  3,  2],
       [-1, -3, -2],
       [ 0,  2,  1]])

In [3]:
np.sort(d14)

array([[ 1,  2,  3],
       [-3, -2, -1],
       [ 0,  1,  2]])

In [4]:
d14

array([[ 1,  3,  2],
       [-1, -3, -2],
       [ 0,  2,  1]])

In [144]:
x1 = d14[0]
x2 = d14[1]
x3 = d14[2]

In [145]:
sorted(x1)

[1, 2, 3]

In [146]:
sorted(x2)

[-3, -2, -1]

In [151]:
sorted(x3)

[0, 1, 2]

In [153]:
reversed(sorted(x3))

In [152]:
list(reversed(sorted(x3)))

[2, 1, 0]

#### Zadanie 4.3.1
Wczytaj macierz `dump_4.3.npy` i wyodrębnij pierwszy wiersz do osobnej zmiennej jako wektor. Zastosuj wszystkie poznane przed chwilą funkcje na tych dwóch zmiennych.

In [154]:
# Q = np.array([
#     [1, 3, 2, 4, 5, -3],
#     [-1, -3, -2, 1, 2, 3]
# ])
# np.save('dumps/dump_4_3.npy', Q)

In [110]:
d15 = np.load('dumps/dump_4_3.npy')

In [111]:
d15

array([[ 1,  3,  2,  4,  5, -3],
       [-1, -3, -2,  1,  2,  3]])

In [170]:
# Q = np.array([
#     [1, 3, 1, 4, 3, -3],
#     [-1, -3, -2, 1, 2, 2]
# ])
# np.save('dumps/dump_4_4.npy', Q)

#### Zadanie 4.5.1:
Utwórz wektor 20 elementowy o wartościach równomiernie rozłożonych w przedziale [1, 10]. Zamień pierwszych 5 elementów na liczbę 0 wykorzystując broadcasting.

In [175]:
x = np.linspace(1, 10, 20)
x[:5] = 0
x

In [178]:
x

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

#### Zadanie 4.6.1:
Utwórz macierz kwadratową za pomocą funkcji `reshape` na wektorze o wartościach z przedziału [20, 28] a następnie wyodrębnij jej przekątną. Zrób to samo na macierzy obróconej prawo-lewo oraz góra-dół

In [8]:
x = np.arange(20, 29).reshape(3, 3)
x

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [14]:
x.diagonal()

array([20, 24, 28])

In [15]:
np.flipud(x).diagonal()

array([26, 24, 22])

In [16]:
np.fliplr(x).diagonal()

array([22, 24, 26])

#### Zadanie 4.7.1:
Poeksperymentuj przez kilka minut z funkcją `concatenate`

In [611]:
# ...

#### Zadanie 5.2.1:
Utwórz tablicę losowych liczb z przedziału [0, 1] o rozmiarze 2 x 3 x 4

In [3]:
np.random.rand(2, 3, 4)

array([[[0.94597957, 0.93450906, 0.46856013, 0.948645  ],
        [0.71821225, 0.66996812, 0.26588345, 0.61119339],
        [0.88907132, 0.14509635, 0.33839295, 0.40472606]],

       [[0.25290391, 0.2152683 , 0.02179888, 0.32453498],
        [0.84321061, 0.05845628, 0.05240209, 0.422573  ],
        [0.66769229, 0.31609437, 0.85592507, 0.31347194]]])

#### Zadanie 5.2.2:
Utwórz wektor ośmiu losowych liczb całkowitych z przedziału [0, 10]

In [4]:
np.random.randint(0, 11, 8)

array([8, 5, 9, 6, 2, 2, 7, 3])

#### Zadanie 5.2.3
Wylosuj jedną liczbe z rozkładu normalnego standardowego. Zamroź stan losowania ustawiając ziarno o dowolnej wartości.

In [241]:
np.random.seed(3)
np.random.randn()

1.7886284734303186